### ISSUE TITLE
Doesn't work on Ubuntu 16

### ISSUE THREAD

**Issue by darkwebdev** [Teradata/nodejs-driver#10]
```
Cannot find module '@teradataprebuilt/fastcall-linux-node-v64'
```
or
```
Cannot load library or library not found: node_modules/@teradataprebuilt/nativelib-linux/teradatasql.so
```

I've fixed it by manually installing `@teradataprebuilt/fastcall-linux-node-v64` and `@teradataprebuilt/nativelib-linux`, but for Mac I don't need to do it, cause mac dependencies are included in `teradata-nodejs-driver`:

```
teradata-nodejs-driver@^1.0.0-beta.2:
...
  dependencies:
    "@teradataprebuilt/fastcall-darwin-node-v57" "^0.2.6"
    "@teradataprebuilt/nativelib-darwin" "^1.0.0-beta.1"
    run-script-os "^1.0.3"
```

I'd suggest either adding these dependencies (they don't affect anything on mac) or at least update the `setup` readme.

**Comment by jeremysmartt** [comment]
Ubuntu tested and working with teradata-nodejs-driver 1.0.0-rc.2

https://www.npmjs.com/package/teradata-nodejs-driver/v/1.0.0-rc.2
