### ISSUE TITLE
Error: Cannot find module 'teradata-nodejs-driver/teradata-connection'

### ISSUE THREAD

**Issue by phanibulusu** [Teradata/nodejs-driver#11]
I am trying to use "teradata-nodejs-driver" package for connecting to teradata from nodejs. But facing below issue. Please help me if any one aware of this issue.

Error: Cannot find module 'teradata-nodejs-driver/teradata-connection'

I installed it prior and installation is clean with out issues. Here is my package.json entry after installation.
"dependencies": {
 "@teradataprebuilt/fastcall-linux-node-v64": "^0.2.6", 
"@teradataprebuilt/nativelib-linux": "^1.0.0-beta.1", 
"teradata-nodejs-driver": "^1.0.0-beta.2", 
"uuid": "^3.3.3" 
}

**Comment by phanibulusu** [comment]
I was using node12.x when above error occurred. 
After, I changed to node10.x this error vanished.

**Comment by jeremysmartt** [comment]
Node.js 12.x now working with teradata-nodejs-driver 1.0.0-rc.2

https://www.npmjs.com/package/teradata-nodejs-driver/v/1.0.0-rc.2
